# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Benoit Liquet
tagline:          'Statistician'
description:      ''
url:              benoit-liquet.github.io
baseurl:          /

author:
  name:           'Benoit Liquet'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/benoit-liquet
